### ISSUE TITLE
TypError on mysmb.py.

### ISSUE THREAD

**Issue by OffSecMan** [worawit/MS17-010#13]
Hello,

When i run the checker.py, I get an error from mysmb.py:

```bash
root@kali:~/Documents/Eternalblue# python checker.py 10.0.0.9
Target OS: 
Traceback (most recent call last):
  File "checker.py", line 42, in <module>
    conn.login(USERNAME, PASSWORD)
  File "/root/Documents/Labs/218/mysmb.py", line 152, in login
    smb.SMB.login(self, user, password, domain, lmhash, nthash, ntlm_fallback)
TypeError: login() takes at most 6 arguments (7 given)
```
Is this an error? Or do I have to give checker.py more/less input?

**Comment by fupinglee** [comment]
i think you should change mysmb.py .

line 137
**old**
`self.smbConn = smbconnection.SMBConnection(self.get_remote_host(), self.get_remote_host(), existingConnection=self, manualNegotiate=True)`
**after change**
`self.smbConn = smbconnection.SMBConnection(self.get_remote_host(), self.get_remote_host(), existingConnection=self)`

line 152
**old**
`smb.SMB.login(self, user, password, domain, lmhash, nthash, ntlm_fallback)`

**after change**
`smb.SMB.login(self, user, password, domain, lmhash, nthash)`

good luck,-)

**Comment by f0r34chb3t4** [comment]
tanks!!
