### ISSUE TITLE
checker error 

### ISSUE THREAD

**Issue by gearcapitan** [worawit/MS17-010#43]
    /home/w/Do/H/N/MS17-010  on   master !18    ✘ INT ▓▒░ python checker.py 10.10.10.178
Traceback (most recent call last):
  File "checker.py", line 40, in <module>
    conn = MYSMB(target)
  File "/home/warmachine/Documentos/HTB/Nest/MS17-010/mysmb.py", line 118, in __init__
    smb.SMB.__init__(self, remote_host, remote_host, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 2427, in __init__
    self.neg_session()
  File "/home/warmachine/Documentos/HTB/Nest/MS17-010/mysmb.py", line 147, in neg_session
    smb.SMB.neg_session(self, extended_security=self.__use_ntlmv2, negPacket=negPacket)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 2642, in neg_session
    smb = self.recvSMB()
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 2506, in recvSMB
    r = self._sess.recv_packet(self.__timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 914, in recv_packet
    data = self.__read(timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 996, in __read
    data = self.read_function(4, timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 983, in non_polling_read
    received = self._sock.recv(bytes_left)
socket.error: [Errno 104] Connection reset by peer

**Comment by tomovic** [comment]
I had the same problem,
download an old Kali Linux and don't update it.
I take the Kali Linux from 2018. Then the code goes.

**Comment by pwnhun73r** [comment]
In the new version of kali 2020.2 my solution was:
**sudo apt-get install python-pip
sudo pip install impacket**
